services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fast_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app/app
  postgres:
    image: postgres
    container_name: fastAPI_CRUD
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fastAPI_db
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
